import './layout/index.html';
import './landing/index.js';
import './navbar/index.js';
import './accounts/index.js';
import './dashboard/index.js';
import './blog/index.js';
import './users/users.js';
import './messages/messages.js';
import './messages/gc.js';